name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        run: |
          cd .vale/styles
          echo $GITHUB_RUN_NUMBER > version.txt
          zip -r RedhatPromptTuning.zip . -i RedhatPromptTuning
          gh release create v$GITHUB_RUN_NUMBER 'RedhatPromptTuning.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
